# Generated by Django 3.0.5 on 2020-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_message_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
